# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=20)),
                ('pro_lang', models.TextField()),
                ('status', models.IntegerField()),
                ('error_result', models.TextField()),
                ('out_result', models.TextField()),
            ],
        ),
    ]
