# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuncompile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compileinfo',
            name='error_result',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='compileinfo',
            name='out_result',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='compileinfo',
            name='pro_lang',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='compileinfo',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
